# -*- coding: utf-8 -*-
"""Apple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BlmYtSKR69VEiLwmoSRML2sRlJieeqrN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot
import plotly.express as px
import plotly.graph_objects as go
#import plotly.io as pio
#pio.templates.default = "plotly_white"

data = pd.read_csv("/content/drive/MyDrive/apple_products.csv")

#Read Data
data.head()

"""# Data Cleaning

**Check Null Values**
"""

print("Null Values")
data.isnull().sum()

"""The dataset does not have any missing values."""

data.describe()

"""**Min sales** = 29999

**Max sales** = 140900

**Min Mrp** = 39900

**Max Mrp** = 149900

**Min star rating** = 4.5

**Min star rating** = 4.7

# Top 10 highest-rated iPhone on Flipkart in India?
"""

Highest_rated = data.sort_values(by=['Star Rating'], ascending=False)
Highest_rated = Highest_rated.head(10)

print(Highest_rated['Product Name'])

print(Highest_rated)

"""# How many rating do the highest-rated iPhone on Flipkart have?"""

iPhone = Highest_rated['Product Name'].value_counts()
print(iPhone)

label = iPhone.index
counts = Highest_rated['Number Of Ratings']
figure = px.bar(Highest_rated, x=label, y = counts,title = "Number of Ratings Highest Rated iPhone")
figure.show()

"""# Which iPhone has the highest number of reviews on Flipkart?"""

label = iPhone.index
counts = Highest_rated['Number Of Reviews']
figure = px.bar(Highest_rated, x=label, y = counts,title = "Number Of Reviews Highest Rated iPhone")
figure.show()

"""# What is the relationships between the sales price of iPhone and the number of rating on Flipkart?"""

data.head(2)

figure = px.scatter(data_frame =data, x ="Number Of Ratings",y = "Sale Price",size='Discount Percentage',trendline='ols',title='Relationship Between Sale Price and Number of Ratings')
figure.show()

"""There is a negative linear relationship between the sales price of iPhone and the number of ratings. It means iPhones with lower sales prices are sold more in india.

# What is the relationships between the Discount percentage of iPhone and the number of rating on Flipkart?
"""

figure = px.scatter(data_frame = data, x = "Number Of Ratings",y = "Discount Percentage", size = "Sale Price", trendline = "ols", title = "Relationship Between Discount Percentage and Number of Ratings")
figure.show()

"""# Most Expensive and least expensive"""

most_expensive = data.loc[data['Sale Price'].idxmax()]
least_expensive = data.loc[data['Sale Price'].idxmin()]

#Display the results
print("Most Expensive iPhone:")
print(most_expensive)

print("\nLeast Expensive iPhone:")
print(least_expensive)

